- name: prepare host
  include_tasks:
    file: prepare_hosts.yml

- name: initialize cluster on master
  include_tasks:
    file: initialize_cluster.yml
  when: inventory_hostname in groups['kube_masters']

- name: join worker nodes
  include_tasks:
    file: join_nodes.yml
