- name: Remove eventual older versions of Docker
  dnf:
    name: 
      - docker-client
      - docker-client-latest 
      - docker-common 
      - docker-latest 
      - docker-latest-logrotate
      - docker-logrotate 
      - docker-selinux 
      - docker-engine-selinux 
      - docker-engine
    state: absent
  
- name:  set up the Docker repository
  dnf:
    name: dnf-plugins-core
    state: present
   
- name: install docker repository
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
     
- name: Install Docker Engine and containerd
  dnf:
    name:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
    state: present

- name: Ensure Docker use systemd cgroupdriver (default cgroupfs)
  lineinfile:
    dest: /etc/docker/daemon.json
    regexp: '"exec-opts":'
    line: '{"exec-opts": ["native.cgroupdriver=systemd"]}'
    create: yes
  tags: debug

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: add user to Docker group
  user:
    name: '{{ user }}'
    groups: docker